name: Add Default Release Type
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            minor release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
